# Copyright (c) 2024, kushdhallod@gmail.com and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class CRMQuotation(Document):
	@frappe.whitelist()
	def update_date(self):
		for d in get_data():
			if d.get('valid_till'):
				doc=frappe.get_doc("Quotation",d.get("quotation"))
				if doc.docstatus==1:
					doc.db_set("valid_till",None)
					doc.db_set("status",'Open')




def get_data():
	return [
  {
    "Sr": 1,
    "quotation": "QTN-00972",
    "docstatus": 1,
    "date": "2024-07-25",
    "valid_till": "2024-07-25",
    "Party": "LEAD-206211745",
    "Title": "Seetha mahalaxmi",
    "Quotation To": "Lead",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 219000,
    "Grand Total (Company Currency)": 219000,
    "Company": "Greentek India Limited",
    "Customer Name": "Seetha mahalaxmi"
  },
  {
    "Sr": 2,
    "quotation": "QTN-00969",
    "docstatus": 1,
    "date": "2024-07-25",
    "valid_till": "2024-07-25",
    "Party": "LEAD-206211695",
    "Title": "Mr Rajagopal Reddy",
    "Quotation To": "Lead",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 562880,
    "Grand Total (Company Currency)": 562880,
    "Company": "Greentek India Limited",
    "Customer Name": "Mr Rajagopal Reddy"
  },
  {
    "Sr": 3,
    "quotation": "QTN-00968",
    "docstatus": 1,
    "date": "2024-07-25",
    "valid_till": "2024-07-25",
    "Party": "LEAD-206204986",
    "Title": "Mr Lokeswara rao",
    "Quotation To": "Lead",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 203791,
    "Grand Total (Company Currency)": 203791,
    "Company": "Greentek India Limited",
    "Customer Name": "Mr Lokeswara rao"
  },
  {
    "Sr": 4,
    "quotation": "QTN-00966-1",
    "docstatus": 1,
    "date": "2024-07-23",
    "valid_till": "2024-07-23",
    "Party": "LEAD-206211623",
    "Title": "Syed Usman",
    "Quotation To": "Lead",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 438260.53,
    "Grand Total (Company Currency)": 438260.53,
    "Company": "Greentek India Limited",
    "Customer Name": "Syed Usman"
  },
  {
    "Sr": 5,
    "quotation": "QTN-00967",
    "docstatus": 1,
    "date": "2024-07-24",
    "valid_till": "2024-07-24",
    "Party": "Aquasol Energy",
    "Title": "Aquasol Energy",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 117237,
    "Grand Total (Company Currency)": 117237,
    "Company": "Greentek India Limited",
    "Customer Name": "Aquasol Energy"
  },
  {
    "Sr": 6,
    "quotation": "QTN-00965",
    "docstatus": 1,
    "date": "2024-07-22",
    "valid_till": "2024-07-22",
    "Party": "SKYGLOW ELECTRICALS AND SOLAR INDUSTRIES PRIVATE LIMITED",
    "Title": "SKYGLOW ELECTRICALS AND SOLAR INDUSTRIES PRIVATE LIMITED",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 222566,
    "Grand Total (Company Currency)": 222566,
    "Company": "Greentek India Limited",
    "Customer Name": "SKYGLOW ELECTRICALS AND SOLAR INDUSTRIES PRIVATE LIMITED"
  },
  {
    "Sr": 7,
    "quotation": "QTN-00964",
    "docstatus": 1,
    "date": "2024-07-22",
    "valid_till": "2024-07-22",
    "Party": "K K Enterprises",
    "Title": "K K Enterprises",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 375580,
    "Grand Total (Company Currency)": 375580,
    "Company": "Greentek India Limited",
    "Customer Name": "K K Enterprises"
  },
  {
    "Sr": 8,
    "quotation": "QTN-00963",
    "docstatus": 1,
    "date": "2024-07-22",
    "valid_till": "2024-07-22",
    "Party": "Shaatit Solar Private Limited",
    "Title": "Shaatit Solar Private Limited",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 92887,
    "Grand Total (Company Currency)": 92887,
    "Company": "Greentek India Limited",
    "Customer Name": "Shaatit Solar Private Limited"
  },
  {
    "Sr": 9,
    "quotation": "QTN-00962-3",
    "docstatus": 1,
    "date": "2024-07-20",
    "valid_till": "2024-07-20",
    "Party": "LEAD-206211574",
    "Title": "Mr Fazil Haneef",
    "Quotation To": "Lead",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 284112,
    "Grand Total (Company Currency)": 284112,
    "Company": "Greentek India Limited",
    "Customer Name": "Mr Fazil Haneef"
  },
  {
    "Sr": 10,
    "quotation": "QTN-00961",
    "docstatus": 1,
    "date": "2024-07-17",
    "valid_till": None,
    "Party": "Adhwaya Energy Solutions",
    "Title": "Adhwaya Energy Solutions",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 510518,
    "Grand Total (Company Currency)": 510518,
    "Company": "Greentek India Limited",
    "Customer Name": "Adhwaya Energy Solutions"
  },
  {
    "Sr": 11,
    "quotation": "QTN-00960-1",
    "docstatus": 1,
    "date": "2024-07-17",
    "valid_till": None,
    "Party": "LEAD-206211411",
    "Title": "Ramakrishna Reddy",
    "Quotation To": "Lead",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 694400,
    "Grand Total (Company Currency)": 694400,
    "Company": "Greentek India Limited",
    "Customer Name": "vensa infrastructure limited"
  },
  {
    "Sr": 12,
    "quotation": "QTN-00959",
    "docstatus": 1,
    "date": "2024-07-17",
    "valid_till": None,
    "Party": "V-Pro Solar Systems",
    "Title": "V-Pro Solar Systems",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 137894,
    "Grand Total (Company Currency)": 137894,
    "Company": "Greentek India Limited",
    "Customer Name": "V-Pro Solar Systems"
  },
  {
    "Sr": 13,
    "quotation": "QTN-00958-1",
    "docstatus": 1,
    "date": "2024-07-16",
    "valid_till": None,
    "Party": "Adhwaya Energy Solutions",
    "Title": "Adhwaya Energy Solutions",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 630509.9,
    "Grand Total (Company Currency)": 630509.9,
    "Company": "Greentek India Limited",
    "Customer Name": "Adhwaya Energy Solutions"
  },
  {
    "Sr": 14,
    "quotation": "QTN-00957-1",
    "docstatus": 1,
    "date": "2024-07-16",
    "valid_till": None,
    "Party": "Adhwaya Energy Solutions",
    "Title": "Adhwaya Energy Solutions",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 504529.59,
    "Grand Total (Company Currency)": 504529.59,
    "Company": "Greentek India Limited",
    "Customer Name": "Adhwaya Energy Solutions"
  },
  {
    "Sr": 15,
    "quotation": "QTN-00956",
    "docstatus": 1,
    "date": "2024-07-16",
    "valid_till": None,
    "Party": "Adhwaya Energy Solutions",
    "Title": "Adhwaya Energy Solutions",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 219129.27,
    "Grand Total (Company Currency)": 219129.27,
    "Company": "Greentek India Limited",
    "Customer Name": "Adhwaya Energy Solutions"
  },
  {
    "Sr": 16,
    "quotation": "QTN-00947",
    "docstatus": 1,
    "date": "2024-07-16",
    "valid_till": "2024-07-16",
    "Party": "Osmium Energy Private Limited",
    "Title": "Osmium Energy Private Limited",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 88630,
    "Grand Total (Company Currency)": 88630,
    "Company": "Greentek India Limited",
    "Customer Name": "Osmium Energy Private Limited"
  },
  {
    "Sr": 17,
    "quotation": "QTN-00944",
    "docstatus": 1,
    "date": "2024-07-11",
    "valid_till": "2024-07-11",
    "Party": "APS@Services",
    "Title": "APS@Services",
    "Quotation To": "Customer",
    "Order Type": "Sales",
    "Status": "Expired",
    "Currency": "INR",
    "Grand Total": 88149,
    "Grand Total (Company Currency)": 88149,
    "Company": "Greentek India Limited",
    "Customer Name": "APS@Services"
  }
]


